name: Valentina Valentini
favicon: null
layout_spectrum: 0.7140564075671136
typography_spectrum: 0.46089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5300903248135
  lightness: 0.2995145167224109
  saturation: 0.9023848336655647
  rhythmicContrast: 0.16848869970999658
purpose: []
