name: Valentina Valentini
favicon: null
layout_spectrum: 0.24874
typography_spectrum: 0.46089
title: Journalist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdd9d7'
    - '#95a5a5'
    - '#5f6f6f'
    - '#455354'
    - '#101b1d'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
