name: Valentina Valentini
favicon: null
layout_spectrum: 0.24874
typography_spectrum: 0.46089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f5ef'
    - '#b9a078'
    - '#7a877d'
    - '#2e1c10'
    - '#564535'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
