typography_spectrum: 0.46089
color:
  brandColors:
    - '#cdd9d7'
    - '#95a5a5'
    - '#5f6f6f'
    - '#455354'
    - '#101b1d'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24874
analytics:
  google: null
  facebook: null
  twitter: null
name: Valentina Valentini
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about
    id: 688d3ef9-9eed-41ab-b7ea-dbde75bd7e26
    type: content
  - name: contact
    id: fb27039c-a588-4a6e-8de3-d1460a572a05
    type: content
  - name: select articles
    id: ece5e98a-fd8f-4a96-9c91-d14c6b8b5eba
    type: content
favicon: null
title: Journalist
description: Entertainment. Travel. Culture.
purpose: []
